### ISSUE TITLE
Typed enqueue, Enqueue<T> 

### ISSUE THREAD

**Issue by weyert** [ahydrax/Hangfire.Atoms#4]
I am wondering whether support for typed jobs could be added? 
In Hangfire itself you can queue jobs via `Enqueue<T>(task => task.Blah());

I am not sure if I can just add the necessary methods mysel or that your code needs changes to support these generics methods. I will experience with it.

**Comment by weyert** [comment]
I think I sorted this by writing an extension class. Would you accept a PR for this?

**Comment by ahydrax** [comment]
Hi @weyert, sure, just send a PR.

**Comment by weyert** [comment]
@ahydrax  I have created a PR to introduce these methods. In Hangfire itself they are using an extension method to add these extra methods only they build on the `IBackgroundJobClient`'s Create-method which accepts an instance of `Job` which isn't available on `IAtomBuilder` hence my current approach. 

Let me know what you think of the PR.

**Comment by ahydrax** [comment]
Hi @weyert , the new version in on [nuget ](https://www.nuget.org/packages/Hangfire.Atoms/0.4.2). Thank you for your contribution
