### ISSUE TITLE
Test case 7 from test suite is failing

### ISSUE THREAD

**Issue by weyert** [ahydrax/Hangfire.Atoms#6]
I was working on extending the test suite to cover my changes in my latest pull request and I noticed something regarding test case 7 and I was wondering if this is expected.

Reproducible steps:
1. Install Redis e.g. run it via Docker `docker run --name ix-redis -p 6379:6379 -d redis`
2. Get the latest master from the repository
3. If needed, change downgrade the TargetFramework version to `netcoreapp2.2` 
4. If needed, add the following to `appsettings.json` when port 5000 is already in use on your system: 
```
  "Kestrel": {
    "EndPoints": {
      "Http": {
        "Url": "http://0.0.0.0:5002"
      }
    }
  }
```
4. Run the application
5. In the Hangfire Dashboard trigger recurring job `Atom test-7`
6. Wait for the job to start being processed
7. Notice that the job gets stuck at 75% when you go to the `Atoms running`-section of the `Jobs`-page
8. Notice that there is still an awaiting job

(full disclosure, I have the if needed steps as this was required on my work notebook)

I was wondering if this is correct behaviour or should the awaited task have been ran?

**Comment by weyert** [comment]
@ahydrax Any idea, if this should be working?

**Comment by ahydrax** [comment]
Hi @weyert if I remember correctly this test should fail every time in order to see if tracking of failed jobs is handled properly.

**Comment by weyert** [comment]
Ah okay, now just looks like it's stuck. I am wondering now if it's possible to schedule a bunch of atomic jobs and then have a ContinuationJobWith which will always get executed even when there are failing jobs? Currently, the continuation job doesn't get called.

**Comment by ahydrax** [comment]
I still didn't find a proper solution how to show that job got stuck and user has to do something about that. Maybe you have some good ideas?

Regarding atom continuations: if I remember correctly you can use `JobContinuationOptions atomProgress = JobContinuationOptions.OnAnyFinishedState` parameter when calling `Schedule|Enqueue|ContinueJobWith`.

**Comment by weyert** [comment]
@ahydrax  I don't have any good ideas but I will think about it. Thanks for the tip I will give it a try :)
